### ISSUE TITLE
CPU and GPU Utilization

### ISSUE THREAD

**Issue by xiafengdongzhi** [laminair/jetson_stats_node_exporter#13]
I want to monitor cpu and gpu usage, but there is only frequency in it, how do I configure it? Thanks！

**Comment by laminair** [comment]
You can do so in two ways: 
1. You add new exports in the exporter.py file. The jetson data is available as a dictionary. You can check the available keys and add additional gauges as desired. Here is the function for exporting GPU metrics:  https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L45
And this is the function for CPU metrics: https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L30

2. Since there is an ever-lasting discussion on whether CPU utilization is a good metric for evaluations (see for example: https://www.brendangregg.com/blog/2017-05-09/cpu-utilization-is-wrong.html), we use the device power consumption as a metric instead. We know the power threshold of the CPU and can infer the power threshold of the GPU based on the maximum total power draw of a jetson device, which provides you with all necessary information to calculate the device utilization. The power consumption metrics are being exported. See here for details: https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L134

**Comment by xiafengdongzhi** [comment]
Thanks,I will try it.

**Comment by xiafengdongzhi** [comment]
> You can do so in two ways:
> 
> 1. You add new exports in the exporter.py file. The jetson data is available as a dictionary. You can check the available keys and add additional gauges as desired. Here is the function for exporting GPU metrics:  https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L45
>    
>    And this is the function for CPU metrics: https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L30
> 2. Since there is an ever-lasting discussion on whether CPU utilization is a good metric for evaluations (see for example: https://www.brendangregg.com/blog/2017-05-09/cpu-utilization-is-wrong.html), we use the device power consumption as a metric instead. We know the power threshold of the CPU and can infer the power threshold of the GPU based on the maximum total power draw of a jetson device, which provides you with all necessary information to calculate the device utilization. The power consumption metrics are being exported. See here for details: https://github.com/laminair/jetson_stats_node_exporter/blob/c037fc016f6406cf07022b03d7646f4232c61379/jetson_stats_node_exporter/exporter.py#L134

Thank you!!! I will try.
